[package]
edition = "2021"
name = "aws-smithy-http-server"
version = "0.55.4"
authors = ["Smithy Rust Server <smithy-rs-server@amazon.com>"]
publish = true
description = """
Server runtime for Smithy Rust Server Framework.
"""
readme = "README.md"
keywords = [
    "smithy",
    "framework",
    "web",
    "api",
    "aws",
]
categories = [
    "asynchronous",
    "web-programming",
    "api-bindings",
]
license = "Apache-2.0"
repository = "https://github.com/awslabs/smithy-rs"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = [
    "--cfg",
    "docsrs",
]

[dependencies.async-trait]
version = "0.1"

[dependencies.aws-smithy-http]
version = "0.55.3"
features = ["rt-tokio"]

[dependencies.aws-smithy-json]
version = "0.55.3"

[dependencies.aws-smithy-types]
version = "0.55.3"

[dependencies.aws-smithy-xml]
version = "0.55.3"

[dependencies.bytes]
version = "1.1"

[dependencies.futures-util]
version = "0.3.16"
default-features = false

[dependencies.http]
version = "0.2"

[dependencies.http-body]
version = "0.4"

[dependencies.hyper]
version = "0.14.12"
features = [
    "server",
    "http1",
    "http2",
    "tcp",
    "stream",
]

[dependencies.lambda_http]
version = "0.7.1"
optional = true

[dependencies.mime]
version = "0.3"

[dependencies.nom]
version = "7"

[dependencies.once_cell]
version = "1.13"

[dependencies.pin-project-lite]
version = "0.2"

[dependencies.regex]
version = "1.5.5"

[dependencies.serde_urlencoded]
version = "0.7"

[dependencies.thiserror]
version = "1.0.0"

[dependencies.tokio]
version = "1.23.1"
features = ["full"]

[dependencies.tower]
version = "0.4.11"
features = [
    "util",
    "make",
]
default-features = false

[dependencies.tower-http]
version = "0.3"
features = [
    "add-extension",
    "map-response-body",
]

[dependencies.tracing]
version = "0.1.35"

[dependencies.uuid]
version = "1"
features = [
    "v4",
    "fast-rng",
]
optional = true

[dev-dependencies.pretty_assertions]
version = "1"

[features]
aws-lambda = ["dep:lambda_http"]
request-id = ["dep:uuid"]
unredacted-logging = []
