# Example changelog entries
# [[aws-sdk-rust]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false }
# author = "rcoh"
#
# [[smithy-rs]]
# message = "Fix typos in module documentation for generated crates"
# references = ["smithy-rs#920"]
# meta = { "breaking" = false, "tada" = false, "bug" = false, "target" = "client | server | all"}
# author = "rcoh"

[[smithy-rs]]
message = "Invert `seen_${var}` to `${var}_seen`, preventing compilation errors in escaped code."
references = ["smithy-rs#2789"]
meta = { "breaking" = false, "tada" = false, "bug" = true, "target" = "server"}
author = "hlbarber"
