[package]
name = "retry-diagnostics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
anyhow = "1.0.79"
http = "1.0.0"
aws-smithy-async = "1.1.4"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
bytes = "1.5.0"
aws-sdk-s3 = "1.14.0"
indicatif = "0.17.7"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
chrono = "0.4.33"

[dev-dependencies]
aws-sdk-dynamodb = "1"
aws-config = "1"
aws-smithy-async = { version = "1.1.4", features = ["test-util"] }
