# Without this configuration, the workspace will be read from `rust-runtime`, causing the build to fail.
[workspace]
members = [
    "pokemon-service",
    "pokemon-service-server-sdk",
    "pokemon-service-client",
    "rpcv2-service",
]

[profile.release]
lto = true
