[build]
target = "wasm32-wasi"

[target.wasm32-wasi]
rustflags = ["-C", "opt-level=1"]
runner = [
    "wasmtime",
    "--disable-cache",
    "--preview2",
    "--wasi-modules=experimental-wasi-http",
]
