# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Canary
on:
  workflow_call:
    inputs:
      pull_request_number:
        description: |
          PR Number: The PR number in which to run canary.
        required: true
        type: string
      commit_sha:
        description: |
          Commit SHA: The SHA of the git commit against which canary runs.
        required: true
        type: string
    secrets:
      SMITHY_RS_CANARY_GITHUB_ACTIONS_ROLE_ARN:
        required: true
      CANARY_LAMBDA_CODE_S3_BUCKET:
        required: true
      CANARY_LAMBDA_TEST_S3_BUCKET:
        required: true
      CANARY_LAMBDA_EXECUTION_ROLE_ARN:
        required: true
      CANARY_LAMBDA_TEST_S3_MRAP_BUCKET_ARN:
        required: true
      CANARY_LAMBDA_TEST_S3_EXPRESS_BUCKET_NAME:
        required: true

# Allow one instance of this workflow per pull request, and cancel older runs when new changes are pushed
concurrency:
  group: canary-yml-${{ inputs.pull_request_number }}
  cancel-in-progress: true

jobs:
  canary:
    name: Canary
    runs-on: smithy_ubuntu-latest_8-core
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        path: smithy-rs
        ref: ${{ inputs.commit_sha }}
    - name: Configure Credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        role-to-assume: ${{ secrets.SMITHY_RS_CANARY_GITHUB_ACTIONS_ROLE_ARN }}
        output-credentials: true
    - name: Run canary
      uses: ./smithy-rs/.github/actions/docker-build
      with:
        action: run-canary
        # TODO(Canary): Replace a list of env variables with a JSON stored in S3
        action-arguments: ${{ secrets.CANARY_LAMBDA_CODE_S3_BUCKET }} ${{ secrets.CANARY_LAMBDA_TEST_S3_BUCKET }} ${{ secrets.CANARY_LAMBDA_EXECUTION_ROLE_ARN }} ${{ secrets.CANARY_LAMBDA_TEST_S3_MRAP_BUCKET_ARN }} ${{ secrets.CANARY_LAMBDA_TEST_S3_EXPRESS_BUCKET_NAME }} ${{ steps.creds.outputs.aws-access-key-id }} ${{ steps.creds.outputs.aws-secret-access-key }} ${{ steps.creds.outputs.aws-session-token }}
