# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# This workflow claims the names of the unpublished crates in this repository
# on crates.io (by publishing a dummy empty package)

# Allow only one crate claim workflow to run at a time
concurrency:
  group: claim-crates-smithy-rs
  cancel-in-progress: true

env:
  rust_version: 1.74.1

name: Claim unpublished crate names on crates.io
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: |
          Repository name: The name of a repository of the format {owner}/{repo} you want to clone.
        required: false
        type: string
      commit_sha:
        description: |
          Commit SHA: The SHA of the git commit to which the current branch is pointed to.
        required: true
        type: string

jobs:
  acquire-base-image:
    name: Acquire Base Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: smithy-rs
        ref: ${{ inputs.commit_sha }}
        fetch-depth: 0
    - name: Acquire base image
      id: acquire
      run: ./smithy-rs/.github/scripts/acquire-build-image
    - name: Upload base image
      uses: actions/upload-artifact@v4
      with:
        name: smithy-rs-base-image
        path: smithy-rs-base-image
        retention-days: 1

  canary:
    name: Canary
    needs:
    - acquire-base-image
    uses: ./.github/workflows/canary.yml
    with:
      pull_request_number: 0
      commit_sha: ${{ inputs.commit_sha }}
    secrets:
      SMITHY_RS_CANARY_GITHUB_ACTIONS_ROLE_ARN: ${{ secrets.SMITHY_RS_CANARY_GITHUB_ACTIONS_ROLE_ARN }}
      CANARY_LAMBDA_CODE_S3_BUCKET: ${{ secrets.CANARY_LAMBDA_CODE_S3_BUCKET }}
      CANARY_LAMBDA_TEST_S3_BUCKET: ${{ secrets.CANARY_LAMBDA_TEST_S3_BUCKET }}
      CANARY_LAMBDA_EXECUTION_ROLE_ARN: ${{ secrets.CANARY_LAMBDA_EXECUTION_ROLE_ARN }}
      CANARY_LAMBDA_TEST_S3_MRAP_BUCKET_ARN: ${{ secrets.CANARY_LAMBDA_TEST_S3_MRAP_BUCKET_ARN }}
      CANARY_LAMBDA_TEST_S3_EXPRESS_BUCKET_NAME: ${{ secrets.CANARY_LAMBDA_TEST_S3_EXPRESS_BUCKET_NAME }}
