# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# This workflow performs a dry run for smithy-rs release. It can be triggered via either cron or manually.
# When ran, it only produces release artifacts, but will not cut a release tag in GitHub or publish to crates.io.

name: Smithy-rs dry run release
run-name: ${{ github.workflow }} ${{ inputs.commit_sha == ''  && 'scheduled' || (inputs.commit_sha) }}
on:
  schedule:
    # Runs 00:00 UTC every day
  - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      commit_sha:
        description: |
          Commit SHA: The SHA of the git commit that you want to release.
          You must use the non-abbreviated SHA (e.g. b2318b0 won't work!).
        required: true
        type: string

# Allow only one release to run at a time
concurrency:
  group: smithy-rs-dry-run-release
  cancel-in-progress: true

jobs:
  smithy-rs-manual-dry-run-release:
    name: Manual dry run release
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/release.yml
    with:
      commit_sha: ${{ inputs.commit_sha }}
      dry_run: true
    secrets:
      RELEASE_AUTOMATION_BOT_PAT: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}

  smithy-rs-scheduled-dry-run-release:
    name: Scheduled dry run release
    if: ${{ github.event_name == 'schedule' }}
    uses: ./.github/workflows/release.yml
    with:
      commit_sha: main
      dry_run: true
    secrets:
      RELEASE_AUTOMATION_BOT_PAT: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
