on:
  workflow_dispatch:

name: Update GitHub Pages

env:
  rust_version: 1.74.1
  release_branch: smithy-rs-release-1.x.y

jobs:
  create-backport-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Prepare backport branch
      run: |
        git fetch
        git checkout origin/main
        git checkout -b "merge-${{ env.release_branch }}-to-main"
        # this assumes the merge runs cleanly without conflicts
        git merge "origin/${{ env.release_branch }}" -m 'Merge remote-tracking branch "origin/${{ env.release_branch }}" into "merge-${{ env.release_branch }}-to-main"'

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
        title: Dummy merge ${{ env.release_branch }} into main
        body: |
          Merge it with `gh pr merge --admin --merge` or manually merge it with the merge commit (not squash merge).

          _By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._
        branch: merge-${{ env.release_branch }}-to-main
        base: main
        draft: true
        labels: |
          needs-sdk-review
