name: Update GitHub Pages

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: |
          Commit SHA: The SHA of the git commit that you want to release.
          You must use the non-abbreviated SHA (e.g. b2318b0 won't work!).
        required: true
        type: string

# Allow only one release to run at a time
concurrency:
  group: smithy-rs-prod-release
  cancel-in-progress: true

jobs:
  smithy-rs-prod-release:
    name: Prod release
    uses: ./.github/workflows/release.yml
    with:
      commit_sha: ${{ inputs.commit_sha }}
      dry_run: false
    secrets:
      RELEASE_AUTOMATION_BOT_PAT: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
      RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN: ${{ secrets.RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN }}
