name: Update GitHub Pages
on:
  workflow_dispatch:

jobs:
  trigger_another_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Another Repository's Workflow
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
        repository: awslabs/aws-sdk-rust
        workflow: .github/workflows/test-job.yml@ysaito/dummy-workflow

        event-type: start-workflow
        client-payload: '{"ref": "${{ github.event.pull_request.head.ref }}"}'
