# This workflow updates the `next` branch with freshly generated
# code from the latest smithy-rs and models that reside in aws-sdk-rust.

name: Update `aws-sdk-rust/next`

on:
  schedule:
    # Runs 00:00 UTC every day
  - cron: 15 3  * * *
  workflow_dispatch:
    inputs:
      commit_sha:
        description: |
          Commit SHA: The SHA of the git commit that you want to release.
          You must use the non-abbreviated SHA (e.g. b2318b0 won't work!).
        required: true
        type: string

# Allow only one release to run at a time
concurrency:
  group: smithy-rs-dry-run-release
  cancel-in-progress: true

jobs:
  smithy-rs-manual-dry-run-release:
    name: Manual dry run release
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/release.yml
    with:
      commit_sha: ${{ inputs.commit_sha }}
      dry_run: true
    secrets:
      RELEASE_AUTOMATION_BOT_PAT: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
      RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN: ${{ secrets.RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN }}

  smithy-rs-scheduled-dry-run-release:
    name: Scheduled dry run release
    if: ${{ github.event_name == 'schedule' }}
    uses: ./.github/workflows/release.yml
    with:
      commit_sha: main
      dry_run: true
    secrets:
      RELEASE_AUTOMATION_BOT_PAT: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
      RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN: ${{ secrets.RELEASE_AUTOMATION_BOT_CRATESIO_TOKEN }}
